# Generated by Django 4.1.3 on 2022-11-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_proyecto_final', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_almacen', models.CharField(max_length=200)),
                ('estado_almacen', models.CharField(max_length=1)),
                ('informacion', models.CharField(max_length=500)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=200)),
                ('estado_cargo', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_epp', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('informacion_epp', models.CharField(max_length=200)),
                ('almacen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_proyecto_final.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('almacen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_proyecto_final.almacen')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_proyecto_final.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_proyecto_final.cargos'),
        ),
    ]
