# Generated by Django 4.1.3 on 2022-11-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proyecto_final', '0003_almacen_cargos_usuario_direccion_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default='', max_length=200),
        ),
    ]
